In [1]:
import xarray as xr
import pandas as pd

In [2]:
dt = xr.open_datatree('./est_topo_dem_10m_elva_igeo7_multi_refinement_level_ds.zarr', engine='zarr')

In [3]:
df = dt['refinement_level_7'].to_dataset().to_dataframe()

In [4]:
df[df['band_1'] == 65.567482]

                      band_1  spatial_ref
zone_id
18804397614039039  65.567482            0

In [15]:
slope_df = pd.read_parquet('./est_topo_slope_10m_elva_igeo7_multi_refinement_level_ds.parquet')

In [28]:
slope_df['time_stamp'] = pd.to_datetime("2025-09-24")

In [2]:
twi_df = pd.read_parquet('./est_topo_twi_10m_elva_healpix_dggrs_multi_refinement_level_ds.parquet')

In [9]:
twi_df.loc[[729583139634226712, 729583139634226713, 729583139634226714, 729583139634227737, 729583139634227738, 729583139634227739, 801640733672770608, 801640733672770609, 801640733672770610, 801640733672770611, 801640733672770612, 801640733672774710, 801640733672780852, 801640733672780853, 801640733672780854, 801640733672780855]]

                       band_1
zone_id
729583139634226712   9.293923
729583139634226713   8.299994
729583139634226714   9.526424
729583139634227737   8.382163
729583139634227738   9.512327
729583139634227739  10.093796
801640733672770608  10.369040
801640733672770609   9.229541
801640733672770610   9.826028
801640733672770611   9.532277
801640733672770612   9.292146
801640733672774710  13.074509
801640733672780852   9.130116
801640733672780853   9.456012
801640733672780854   9.981297
801640733672780855   9.388947

                       band_1 time_stamp
zone_id
1017813515838448018  6.910739 2025-09-23
1017813515838448025  6.898093 2025-09-23
1017813515838448027  6.843788 2025-09-23
1017813515838464400  6.970399 2025-09-23
1017813515838464407  6.959073 2025-09-23
...                       ...        ...
1017813515838742937  6.930196 2025-09-24
1017813515838792093  6.761299 2025-09-24
1017813515838808479  6.781841 2025-09-24
945755921761013965   6.856591 2025-09-24
945755921761022157   6.688850 2025-09-24

[66 rows x 2 columns]